# Use official Python image
FROM python:3.9-slim

# Set working directory
WORKDIR /app

# Copy Python app
COPY flaskapp.py .

# Install Flask
RUN pip install flask

# Expose port
EXPOSE 5000

# Run the app
CMD ["python", "flaskapp.py"]
